services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing-emulators-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${SYNCTHING_CONFIG_FOLDER:-./config}:/config
      - ${SYNCTHING_DATA_FOLDER}:/data
    restart: unless-stopped
    networks:
      external:
        ipv4_address: ${SYNCTHING_IP}

networks:
  external:
    external: true
    name: ${EXTERNAL_NETWORK_NAME}
